name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "Test" ]
    paths:
      - "app/**"   # chỉ khi có thay đổi trong app/
  pull_request:
    branches: [ "Test" ]
    paths:
      - "app/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleUniversalDebug

    - name: Build Release
      run: ./gradlew assembleUniversalRelease

    - name: Upload a Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rvxp-ci-debug-apk
        path: app/build/outputs/apk/universal/debug

    - name: Upload a Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rvxp-ci-release-apk
        path: |
          app/build/outputs/apk/universal/release
          app/build/outputs/mapping/universalRelease/mapping.txt
